spring.application.name=governance-service
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/governance_db
spring.datasource.username=postgres
spring.datasource.password=122127

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092